services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    command: ["start-dev"]
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME={KC_ADMIN_USER}
      - KC_BOOTSTRAP_ADMIN_PASSWORD={KC_ADMIN_PASS}
    volumes:
      - ./keycloak_data:/opt/keycloak/data
